Repository openshift/ci-operator-prowgen, pull requests merged in 2018-09, with the labels that each got.

#10 Generated postsubmits should have `branch` set
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
Labels: approved, lgtm, size/M

#9 Change the ci-operator config format to YAML
  README.md
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
Labels: approved, lgtm, size/XL

#11 Fix triggering regexp
  GENERATOR.md
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
Labels: approved, lgtm, size/S

#12 Add resource constraints to generated jobs
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
Labels: approved, lgtm, size/M

#13 Warn when generated job name is longer than 63 chars
  Gopkg.toml
  cmd/ci-operator-prowgen/main.go
  pkg/jobconfig/files.go
Labels: approved, lgtm, size/M

#15 Expand owners
  OWNERS
Labels: lgtm, size/XS

#18 Sort jobs by name when generating and determinizing
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  cmd/determinize-prow-jobs/main.go
Labels: approved, lgtm, size/L

#21 Always pull the images for tests
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
Labels: approved, size/M

#19 Refactor generator to write at the directory level
  Makefile
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  cmd/determinize-prow-jobs/main.go
  pkg/jobconfig/files.go
  pkg/jobconfig/files_test.go
  test/integration/data/input/config/super/duper/master.yaml
  test/integration/data/input/config/super/duper/release-3.11.yaml
  test/integration/data/input/jobs/super/duper/super-duper-master-postsubmits.yaml
  test/integration/data/input/jobs/super/duper/super-duper-master-presubmits.yaml
  test/integration/data/input/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
  test/integration/data/input/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
  test/integration/data/output/jobs/super/duper/super-duper-master-postsubmits.yaml
  test/integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/integration/data/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
  test/integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
  test/integration/run.sh
Labels: approved, lgtm, size/XXL

#22 Don't write old jobs if they're being written elsewhere
  pkg/jobconfig/files.go
  pkg/jobconfig/files_test.go
Labels: approved, lgtm, size/M, size/S

#20 Honor specific fields in Prow configuration
  GENERATOR.md
  README.md
  pkg/jobconfig/files.go
  pkg/jobconfig/files_test.go
  test/integration/data/input/jobs/super/duper/super-duper-master-presubmits.yaml
  test/integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
Labels: approved, lgtm, size/L

#23 Small fixes for generating everything
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  test/integration/data/output/jobs/super/duper/super-duper-master-postsubmits.yaml
  test/integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/integration/data/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
  test/integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
Labels: approved, lgtm, size/M
