Repository openshift/ci-operator-prowgen, pull requests merged in 2018-08, with the labels that each got.

#1 Fix gitignore, add code and images
  .gitignore
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  images/ci-operator-prowgen/Dockerfile
Labels: approved, lgtm, size/XXL

#3 Require gofmt -s on the repo when linting
  Makefile
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
Labels: approved, lgtm, size/L

#2 Remove the `--full-repo` mode
  README.md
  cmd/ci-operator-prowgen/main.go
Labels: approved, lgtm, size/M

#5 Improve the frontend
  README.md
  cmd/ci-operator-prowgen/main.go
Labels: approved, lgtm, size/L

#6 Add a simple program to make Prow job config ordering deterministic
  cmd/ci-operator-prowgen/main.go
  cmd/determinize-prow-jobs/main.go
  images/determinize-prow-jobs/Dockerfile
  pkg/jobconfig/files.go
Labels: approved, lgtm, size/L

#8 Document what do we generate on what input
  GENERATOR.md
  README.md
Labels: approved, lgtm, size/L

#7 Label images postsubmit if images are promoted to 'openshift'
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
Labels: approved, lgtm, size/L
