Repository openshift/ci-operator-prowgen, pull requests merged in 2018-10, with the labels that each got.

#26 Sort fields in PodSpec for deterministic output
  cmd/ci-operator-prowgen/main_test.go
  pkg/jobconfig/files.go
  test/integration/data/output/jobs/super/duper/super-duper-master-postsubmits.yaml
  test/integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/integration/data/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
  test/integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
Labels: approved, lgtm, size/L

#27 Only sort args for ci-operator
  pkg/jobconfig/files.go
Labels: approved, lgtm, size/XS

#25 change config map usage.
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  test/integration/data/output/jobs/super/duper/super-duper-master-postsubmits.yaml
  test/integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/integration/data/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
  test/integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
Labels: approved, lgtm, size/M

#30 Move the test data to an appropriate location
  test/integration/data/input/config/super/duper/super-duper-master.yaml
  test/integration/data/input/config/super/duper/super-duper-release-3.11.yaml
  test/integration/data/output/jobs/super/duper/super-duper-master-postsubmits.yaml
  test/integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/integration/data/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
  test/integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
Labels: approved, lgtm, size/S

#28 Ensure all additional args are in the --key=val form
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
Labels: approved, lgtm, size/S

#4 Generate e2e test from ci-operator config
  Gopkg.lock
  README.md
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  test/integration/data/input/config/super/duper/super-duper-master.yaml
  test/integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
  vendor/github.com/openshift/ci-operator/OWNERS
  vendor/github.com/openshift/ci-operator/TEMPLATES.md
  vendor/github.com/openshift/ci-operator/VALIDATIONS.md
  vendor/github.com/openshift/ci-operator/cmd/ci-operator/main.go
  vendor/github.com/openshift/ci-operator/pkg/api/config.go
  vendor/github.com/openshift/ci-operator/pkg/api/config_test.go
  vendor/github.com/openshift/ci-operator/pkg/api/types.go
  vendor/github.com/openshift/ci-operator/pkg/defaults/defaults.go
  vendor/github.com/openshift/ci-operator/pkg/steps/input_env.go
  vendor/github.com/openshift/ci-operator/pkg/steps/promote.go
  vendor/github.com/openshift/ci-operator/pkg/steps/rpm_server.go
  vendor/github.com/openshift/ci-operator/pkg/steps/source.go
  vendor/github.com/openshift/ci-operator/test/template.yaml
Labels: approved, lgtm, size/XXL

#31 Stop adding cluster profile to installer tests
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
Labels: approved, lgtm, size/L

#32 Use cluster profile instead of target cloud
  Gopkg.lock
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  test/integration/data/input/config/super/duper/super-duper-master.yaml
  test/integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
  vendor/github.com/openshift/ci-operator/CONFIGURATION.md
  vendor/github.com/openshift/ci-operator/pkg/api/config.go
  vendor/github.com/openshift/ci-operator/pkg/api/config_test.go
  vendor/github.com/openshift/ci-operator/pkg/api/types.go
Labels: approved, lgtm, size/L

#33 Update ci-operator vendor
  Gopkg.lock
  vendor/github.com/openshift/ci-operator/pkg/api/config.go
Labels: approved, lgtm, size/XS, ¯\_(ツ)_/¯

#35 Validate configuration files
  Gopkg.lock
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  test/integration/data/input/config/super/duper/super-duper-master.yaml
  test/integration/data/input/config/super/duper/super-duper-release-3.11.yaml
  vendor/github.com/openshift/ci-operator/ARCHITECTURE.md
  vendor/github.com/openshift/ci-operator/CONFIGURATION.md
  vendor/github.com/openshift/ci-operator/README.md
  vendor/github.com/openshift/ci-operator/cmd/ci-operator/main.go
  vendor/github.com/openshift/ci-operator/pkg/api/config.go
  vendor/github.com/openshift/ci-operator/pkg/api/config_test.go
  vendor/github.com/openshift/ci-operator/pkg/api/types.go
  vendor/github.com/openshift/ci-operator/pkg/defaults/defaults.go
  vendor/github.com/openshift/ci-operator/pkg/steps/template.go
  vendor/github.com/openshift/ci-operator/pkg/steps/test.go
Labels: approved, lgtm, size/L

#37 When generating the postsubmit images job, only promote on exact matches
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  pkg/jobconfig/files.go
  test/integration/data/output/jobs/super/duper/super-duper-master-postsubmits.yaml
  test/integration/data/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
Labels: approved, lgtm, size/L

#36 Add new openshift-ansible test types and profiles in the generator
  Gopkg.lock
  cmd/ci-operator-prowgen/main.go
  vendor/github.com/openshift/ci-operator/CONFIGURATION.md
  vendor/github.com/openshift/ci-operator/pkg/api/config.go
  vendor/github.com/openshift/ci-operator/pkg/api/config_test.go
  vendor/github.com/openshift/ci-operator/pkg/api/types.go
Labels: approved, lgtm, size/L

#39 Fix template name for custom openshift-ansible provisioner
  cmd/ci-operator-prowgen/main.go
Labels: approved, lgtm, size/XS

#40 Add openstack's cluster profile
  Gopkg.lock
  cmd/ci-operator-prowgen/main.go
  vendor/github.com/openshift/ci-operator/TEMPLATES.md
  vendor/github.com/openshift/ci-operator/cmd/ci-operator/main.go
  vendor/github.com/openshift/ci-operator/pkg/api/config.go
  vendor/github.com/openshift/ci-operator/pkg/api/types.go
  vendor/github.com/openshift/ci-operator/pkg/steps/template.go
Labels: approved, lgtm, size/L
