Repository openshift/ci-operator-prowgen, pull requests merged in 2019-05, with the labels that each got.

#155 Revert "rehearse: use updateconfig for template CMs"
  pkg/config/template.go
  pkg/config/template_test.go
  pkg/rehearse/jobs.go
  test/pj-rehearse-integration/expected.yaml
  test/pj-rehearse-integration/master/cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#154 Update references to input images on bump
  cmd/config-brancher/main.go
  cmd/config-brancher/main_test.go
  pkg/promotion/promotion.go
Labels: approved, lgtm, size/L

#156 rehearse: use full paths, modify tests
  pkg/config/release.go
  pkg/config/release_test.go
  pkg/config/template.go
  pkg/config/template_test.go
  pkg/diffs/diffs.go
  pkg/diffs/diffs_test.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
  pkg/rehearse/metrics.go
  test/pj-rehearse-integration/candidate/ci-operator/templates/subdir/test-template.yaml
  test/pj-rehearse-integration/expected.yaml
  test/pj-rehearse-integration/master/ci-operator/templates/subdir/test-template.yaml
Labels: approved, lgtm, size/L

#157 update test-infra vendors
  cmd/ci-operator-prowgen/main_test.go
  go.mod
  go.sum
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
  vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/types.go
  vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/zz_generated.deepcopy.go
  vendor/k8s.io/test-infra/prow/config/config.go
  vendor/k8s.io/test-infra/prow/config/jobs.go
  vendor/k8s.io/test-infra/prow/config/tide.go
  vendor/k8s.io/test-infra/prow/gcsupload/run.go
  vendor/k8s.io/test-infra/prow/github/client.go
  vendor/k8s.io/test-infra/prow/kube/BUILD.bazel
  vendor/k8s.io/test-infra/prow/kube/client.go
  vendor/k8s.io/test-infra/prow/kube/config.go
  vendor/k8s.io/test-infra/prow/plugins/verify-owners/BUILD.bazel
  vendor/k8s.io/test-infra/prow/plugins/verify-owners/verify-owners.go
  vendor/k8s.io/test-infra/prow/pod-utils/decorate/podspec.go
  vendor/k8s.io/test-infra/prow/pod-utils/gcs/BUILD.bazel
  vendor/k8s.io/test-infra/prow/pod-utils/gcs/metadata.go
  vendor/k8s.io/test-infra/prow/pod-utils/gcs/upload.go
  vendor/k8s.io/test-infra/prow/repoowners/repoowners.go
  vendor/k8s.io/test-infra/prow/slack/BUILD.bazel
  vendor/k8s.io/test-infra/prow/slack/client.go
  vendor/k8s.io/test-infra/testgrid/metadata/junit/junit.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#158 add gcp cluster type for selection
  pkg/rehearse/jobs.go
Labels: approved, lgtm, size/XS

#160 Add hongkailiu to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#162 Scaleup job no longer needs release RPMs
  cmd/ci-operator-prowgen/main.go
Labels: approved, lgtm, size/XS

#163 Revert "Scaleup job no longer needs release RPMs"
  cmd/ci-operator-prowgen/main.go
Labels: approved, lgtm, size/XS

#159 rehearse: use updateconfig for template CMs
  cmd/pj-rehearse/main.go
  pkg/config/release.go
  pkg/config/template.go
  pkg/config/template_test.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
  test/pj-rehearse-integration/expected.yaml
  test/pj-rehearse-integration/master/cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L

#161 Generate ci-operator jobs reporting failures to Sentry
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
Labels: approved, lgtm, size/L

#166 Use the correct branch for updating input images
  cmd/config-brancher/main.go
Labels: approved, lgtm, size/XS

#167 rehearse: use git to identify changed templates
  cmd/pj-rehearse/main.go
  pkg/config/release.go
  pkg/config/release_test.go
  pkg/config/template.go
  pkg/config/template_test.go
  pkg/diffs/diffs.go
  pkg/diffs/diffs_test.go
  pkg/rehearse/jobs.go
  pkg/rehearse/metrics_test.go
  test/pj-rehearse-integration/expected.yaml
Labels: approved, lgtm, size/L

#169 cmd/ci-operator-prowgen: add azure4 cluster profile handling
  cmd/ci-operator-prowgen/main.go
  go.mod
  go.sum
  vendor/github.com/openshift/ci-operator/pkg/api/config.go
  vendor/github.com/openshift/ci-operator/pkg/api/types.go
  vendor/github.com/peterbourgon/diskv/diskv.go
  vendor/github.com/sirupsen/logrus/.travis.yml
  vendor/github.com/sirupsen/logrus/README.md
  vendor/github.com/sirupsen/logrus/entry.go
  vendor/github.com/sirupsen/logrus/logger.go
  vendor/github.com/sirupsen/logrus/logrus.go
  vendor/github.com/sirupsen/logrus/terminal_check_aix.go
  vendor/github.com/sirupsen/logrus/terminal_check_notappengine.go
  vendor/github.com/sirupsen/logrus/text_formatter.go
  vendor/golang.org/x/sync/semaphore/semaphore.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#164 Set RPM_REPO_CRIO_DIR for 4.x scaleup tasks
  cmd/ci-operator-prowgen/main.go
Labels: approved, lgtm, size/XS

#170 Use upstream default trigger regexes for jobs
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
Labels: approved, lgtm, size/M
