Repository openshift/ci-operator-prowgen, pull requests merged in 2019-06, with the labels that each got.

#168 rehearse: unify type for profiles and templates
  pkg/config/release.go
  pkg/config/release_test.go
  pkg/config/template.go
  pkg/config/template_test.go
  pkg/diffs/diffs.go
  pkg/diffs/diffs_test.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
  pkg/rehearse/metrics.go
  pkg/rehearse/metrics_test.go
  test/pj-rehearse-integration/expected.yaml
Labels: approved, lgtm, size/L

#172 Trim pesky whitespace from token read from a file
  cmd/repo-brancher/main.go
Labels: approved, lgtm, size/XS

#173 Bump test-infra to get retitle plugin
  go.mod
  go.sum
  vendor/k8s.io/test-infra/prow/bugzilla/client.go
  vendor/k8s.io/test-infra/prow/github/client.go
  vendor/k8s.io/test-infra/prow/github/types.go
  vendor/k8s.io/test-infra/prow/hook/BUILD.bazel
  vendor/k8s.io/test-infra/prow/hook/plugins.go
  vendor/k8s.io/test-infra/prow/plugins/BUILD.bazel
  vendor/k8s.io/test-infra/prow/plugins/approve/approvers/owners.go
  vendor/k8s.io/test-infra/prow/plugins/bugzilla/bugzilla.go
  vendor/k8s.io/test-infra/prow/plugins/project/project.go
  vendor/k8s.io/test-infra/prow/plugins/retitle/BUILD.bazel
  vendor/k8s.io/test-infra/prow/plugins/retitle/retitle.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#174 don't pickup template jobs that will be already rehearsed
  cmd/pj-rehearse/main.go
  pkg/rehearse/jobs.go
Labels: approved, lgtm, size/S

#176 Check that no config file matches more than one glob
  cmd/config-shard-validator/main.go
Labels: approved, lgtm, size/XS

#177 Add link to openshift/ci-tools
  README.md
Labels: approved, lgtm, size/XS
