Repository openshift/ci-operator-prowgen, pull requests merged in 2019-02, with the labels that each got.

#60 Better logging, job validation and unitests.
  cmd/pj-rehearse/main.go
  pkg/diffs/diffs.go
  pkg/diffs/diffs_test.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
Labels: approved, lgtm, size/L

#68 Improve failure mode messaging to the user
  cmd/pj-rehearse/main.go
  pkg/diffs/diffs.go
  pkg/diffs/diffs_test.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
Labels: approved, lgtm, size/M

#70 Add a flag to send debug output to a separate file
  cmd/pj-rehearse/main.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
Labels: approved, lgtm, size/L

#72 Generate trigger regex as upstream does
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  test/integration/data/input/jobs/super/duper/super-duper-master-presubmits.yaml
  test/integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
Labels: approved, lgtm, size/M

#69 Properly propagate more failures and unit test all the things!
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
Labels: approved, lgtm, size/L

#71 Embed branch in rehearsed job's context
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
Labels: approved, lgtm, size/L

#73 Move ExecuteJobs logic to an executor.
  cmd/pj-rehearse/main.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
Labels: approved, lgtm, size/L

#75 Force rehearsals to have an unified trigger
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
Labels: approved, lgtm, size/M

#76 unexport variables, also add some comments.
  pkg/rehearse/jobs.go
Labels: approved, lgtm, size/S

#77 Strip CPU limits from prowjobs directly due to cfs_quota issues
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  test/integration/data/input/jobs/super/duper/super-duper-master-presubmits.yaml
  test/integration/data/output/jobs/super/duper/super-duper-master-postsubmits.yaml
  test/integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/integration/data/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
  test/integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
Labels: approved, lgtm, size/M

#78 Limit rehearsals to 15 jobs
  cmd/pj-rehearse/main.go
  pkg/rehearse/jobs.go
Labels: approved, lgtm, size/S

#74 Add end-to-end test for pj-rehearse
  Makefile
  pkg/rehearse/jobs.go
  test/pj-rehearse-integration/candidate/ci-operator/config/super/duper/super-duper-master.yaml
  test/pj-rehearse-integration/candidate/ci-operator/config/super/trooper/super-trooper-master.yaml
  test/pj-rehearse-integration/candidate/ci-operator/jobs/super/duper/super-duper-master-presubmits.yaml
  test/pj-rehearse-integration/candidate/ci-operator/jobs/super/trooper/super-trooper-master-presubmits.yaml
  test/pj-rehearse-integration/candidate/cluster/ci/config/prow/config.yaml
  test/pj-rehearse-integration/expected_jobs.yaml
  test/pj-rehearse-integration/master/ci-operator/config/super/duper/super-duper-master.yaml
  test/pj-rehearse-integration/master/ci-operator/config/super/trooper/super-trooper-master.yaml
  test/pj-rehearse-integration/master/ci-operator/jobs/super/duper/super-duper-master-presubmits.yaml
  test/pj-rehearse-integration/master/ci-operator/jobs/super/trooper/super-trooper-master-presubmits.yaml
  test/pj-rehearse-integration/master/cluster/ci/config/prow/config.yaml
  test/pj-rehearse-integration/run.sh
  test/prowgen-integration/data/input/config/super/duper/super-duper-master.yaml
  test/prowgen-integration/data/input/config/super/duper/super-duper-release-3.11.yaml
  test/prowgen-integration/data/input/jobs/super/duper/super-duper-master-postsubmits.yaml
  test/prowgen-integration/data/input/jobs/super/duper/super-duper-master-presubmits.yaml
  test/prowgen-integration/data/input/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
  test/prowgen-integration/data/input/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
  test/prowgen-integration/run.sh
Labels: approved, lgtm, size/XXL

#80 add optional:true to rehearsal jobs
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
Labels: approved, lgtm, size/XS

#83 bump: Get the latest ci-operator for validation correction
  Gopkg.lock
  vendor/github.com/openshift/ci-operator/CONFIGURATION.md
  vendor/github.com/openshift/ci-operator/cmd/ci-operator/main.go
  vendor/github.com/openshift/ci-operator/pkg/api/config.go
  vendor/github.com/openshift/ci-operator/pkg/api/config_test.go
  vendor/github.com/openshift/ci-operator/pkg/api/types.go
  vendor/github.com/openshift/ci-operator/pkg/defaults/defaults.go
  vendor/github.com/openshift/ci-operator/pkg/defaults/defaults_test.go
  vendor/github.com/openshift/ci-operator/pkg/steps/artifacts.go
  vendor/github.com/openshift/ci-operator/pkg/steps/artifacts_test.go
  vendor/github.com/openshift/ci-operator/pkg/steps/pod.go
  vendor/github.com/openshift/ci-operator/pkg/steps/pod_test.go
  vendor/github.com/openshift/ci-operator/pkg/steps/promote.go
  vendor/github.com/openshift/ci-operator/pkg/steps/release/create_release.go
  vendor/github.com/openshift/ci-operator/pkg/steps/run.go
  vendor/github.com/openshift/ci-operator/pkg/steps/source.go
  vendor/github.com/openshift/ci-operator/pkg/steps/template.go
  vendor/github.com/openshift/ci-operator/test/template.yaml
Labels: approved, lgtm, size/XXL

#82 Images in the 'ocp' namespace should have the release payload
  GENERATOR.md
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
Labels: approved, lgtm, size/M

#84 group constants
  pkg/rehearse/jobs.go
Labels: approved, lgtm, size/S

#85 exit if there are no jobs to rehearse
  cmd/pj-rehearse/main.go
Labels: approved, lgtm, size/XS

#86 Only generate `--promote` jobs on those that have promotion config
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  test/prowgen-integration/data/input/config/super/duper/super-duper-master.yaml
  test/prowgen-integration/data/input/config/super/duper/super-duper-release-3.11.yaml
Labels: approved, lgtm, size/L

#89 Separate out promotion check
  cmd/ci-operator-prowgen/main.go
  pkg/promotion/promotion.go
  pkg/promotion/promotion_test.go
Labels: approved, lgtm, size/L

#90 Break out loading logic
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  pkg/config/load.go
  pkg/config/load_test.go
Labels: approved, lgtm, size/XL

#81 Add `allow-volumes` flag. Split filtering logic from the executor
  cmd/pj-rehearse/main.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
Labels: approved, lgtm, size/L

#67 pj-rehearse: tests for main, using integration data
  cmd/pj-rehearse/main_test.go
Labels: approved, lgtm, size/L

#95 Fix the failure messages in rehearse integration test
  cmd/pj-rehearse/main_test.go
Labels: approved, lgtm, size/XS

#94 RPM_REPO_OPENSHIFT_ORIGIN should add 'origin-v' prefix if release doesn't have it
  cmd/ci-operator-prowgen/main.go
Labels: approved, lgtm, size/XS

#93 Generated openshift-ansible tests for 4.0 should use scaleup
  cmd/ci-operator-prowgen/main.go
Labels: approved, lgtm, size/XS

#96 Discover new/changed ci-operator configs
  cmd/pj-rehearse/main.go
  pkg/config/load.go
  pkg/diffs/diffs.go
  pkg/diffs/diffs_test.go
  test/pj-rehearse-integration/candidate/ci-operator/config/super/duper/super-duper-ciop-cfg-change.yaml
  test/pj-rehearse-integration/candidate/ci-operator/jobs/super/duper/super-duper-ciop-cfg-change-presubmits.yaml
  test/pj-rehearse-integration/master/ci-operator/config/super/duper/super-duper-ciop-cfg-change.yaml
  test/pj-rehearse-integration/master/ci-operator/jobs/super/duper/super-duper-ciop-cfg-change-presubmits.yaml
Labels: approved, lgtm, size/L

#98 Remove duplicate ci-operator config loading code
  Gopkg.lock
  cmd/pj-rehearse/main.go
  cmd/pj-rehearse/main_test.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
  test/pj-rehearse-integration/expected_jobs.yaml
  vendor/github.com/openshift/ci-operator/CONFIGURATION.md
  vendor/github.com/openshift/ci-operator/cmd/ci-operator/main.go
  vendor/github.com/openshift/ci-operator/pkg/api/config.go
  vendor/github.com/openshift/ci-operator/pkg/api/config_test.go
  vendor/github.com/openshift/ci-operator/pkg/api/job_spec.go
  vendor/github.com/openshift/ci-operator/pkg/api/types.go
  vendor/github.com/openshift/ci-operator/pkg/defaults/defaults.go
  vendor/github.com/openshift/ci-operator/pkg/defaults/defaults_test.go
  vendor/github.com/openshift/ci-operator/pkg/load/load.go
  vendor/github.com/openshift/ci-operator/pkg/load/load_test.go
  vendor/github.com/openshift/ci-operator/pkg/steps/git_source.go
  vendor/github.com/openshift/ci-operator/pkg/steps/pod.go
  vendor/github.com/openshift/ci-operator/pkg/steps/pod_test.go
  vendor/github.com/openshift/ci-operator/pkg/steps/project_image.go
  vendor/github.com/openshift/ci-operator/pkg/steps/rpm_server.go
  vendor/github.com/openshift/ci-operator/pkg/steps/run.go
  vendor/github.com/openshift/ci-operator/pkg/steps/source.go
Labels: approved, lgtm, size/XXL
