Repository openshift/ci-operator-prowgen, pull requests merged in 2019-01, with the labels that each got.

#48 Only promote to openshift:origin-v4.0 from master branches
  cmd/ci-operator-prowgen/main.go
Labels: approved, lgtm, size/S

#52 Init: Find which presubmits have to be executed.
  cmd/pj-rehearse/main.go
  images/pj-rehearse/Dockerfile
  pkg/diffs/diffs.go
Labels: approved, lgtm, size/L

#54 Add an option for suppressing failures
  cmd/pj-rehearse/main.go
Labels: approved, lgtm, size/S

#55 Suppress rehearsing jobs with additional volumes
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
Labels: approved, lgtm, size/M

#57 skip changed jobs with no branches.
  pkg/rehearse/jobs.go
Labels: approved, lgtm, size/XS

#51 Watch jobs during rehearsal and report results
  cmd/pj-rehearse/main.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
Labels: approved, lgtm, size/L

#58 Allow `openshift-4.0` branches to be promoted
  cmd/ci-operator-prowgen/main.go
Labels: approved, lgtm, size/XS

#63 remove unused struct.
  cmd/ci-operator-prowgen/main.go
Labels: approved, lgtm, size/XS

#56 Change from configMaps to master's worktree
  cmd/pj-rehearse/main.go
  pkg/diffs/diffs.go
Labels: approved, lgtm, size/M

#65 Remove assumption that tag_specification is set
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
Labels: approved, lgtm, size/S

#66 Check out tested revision back after getting master Prow config
  cmd/pj-rehearse/main.go
Labels: approved, lgtm, size/M
