Repository openshift/ci-operator-prowgen, pull requests merged in 2019-03, with the labels that each got.

#99 rehearse: optimize git manipulation when loading configs
  cmd/pj-rehearse/main.go
  cmd/pj-rehearse/main_test.go
  pkg/config/release.go
  pkg/config/template.go
  pkg/diffs/diffs.go
Labels: approved, lgtm, size/L

#97 Add flag to derive JobSpec from local changes
  cmd/pj-rehearse/main.go
  pkg/config/release.go
  test/pj-rehearse-integration/run.sh
Labels: approved, lgtm, size/M

#102 The new upgrade job is supported as part of the ci-operator
  Gopkg.lock
  cmd/ci-operator-prowgen/main.go
  pkg/diffs/diffs_test.go
  test/pj-rehearse-integration/expected_jobs.yaml
  vendor/github.com/openshift/ci-operator/CONFIGURATION.md
  vendor/github.com/openshift/ci-operator/cmd/ci-operator/main.go
  vendor/github.com/openshift/ci-operator/pkg/api/config.go
  vendor/github.com/openshift/ci-operator/pkg/api/parameters.go
  vendor/github.com/openshift/ci-operator/pkg/api/parameters_test.go
  vendor/github.com/openshift/ci-operator/pkg/api/types.go
  vendor/github.com/openshift/ci-operator/pkg/defaults/defaults.go
  vendor/github.com/openshift/ci-operator/pkg/steps/artifacts.go
  vendor/github.com/openshift/ci-operator/pkg/steps/pod.go
  vendor/github.com/openshift/ci-operator/pkg/steps/release/create_release.go
  vendor/github.com/openshift/ci-operator/pkg/steps/release/promote.go
  vendor/github.com/openshift/ci-operator/pkg/steps/release/release_images.go
  vendor/github.com/openshift/ci-operator/pkg/steps/release_images.go
  vendor/github.com/openshift/ci-operator/pkg/steps/rpm_injection.go
  vendor/github.com/openshift/ci-operator/pkg/steps/source.go
  vendor/github.com/openshift/ci-operator/pkg/steps/template.go
  vendor/github.com/openshift/ci-operator/pkg/steps/write_params.go
  vendor/github.com/openshift/ci-operator/pkg/steps/write_params_test.go
Labels: approved, lgtm, size/XXL

#103 Better diff output on tests.
  pkg/diffs/diffs_test.go
  pkg/jobconfig/files_test.go
  pkg/rehearse/jobs_test.go
Labels: approved, lgtm, size/S

#101 Rehearse jobs that use changed ci-operator configs
  cmd/pj-rehearse/main.go
  cmd/pj-rehearse/main_test.go
  pkg/config/jobs.go
  pkg/config/jobs_test.go
  pkg/config/release.go
  pkg/diffs/diffs.go
  pkg/diffs/diffs_test.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
  test/pj-rehearse-integration/expected_jobs.yaml
Labels: approved, lgtm, size/L

#105 Load token from a file, not plaintext in options
  cmd/repo-brancher/main.go
  test/pj-rehearse-integration/expected_jobs.yaml
Labels: approved, lgtm, size/S

#106 Hide token values from logging output
  cmd/repo-brancher/main.go
Labels: approved, lgtm, size/S

#104 Handle sharded ci-operator CMs in rehearse
  pkg/config/load.go
  pkg/config/load_test.go
  pkg/config/release.go
  pkg/diffs/diffs.go
  pkg/diffs/diffs_test.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
  test/pj-rehearse-integration/candidate/ci-operator/jobs/super/duper/super-duper-ciop-cfg-change-presubmits.yaml
  test/pj-rehearse-integration/candidate/ci-operator/jobs/super/duper/super-duper-master-presubmits.yaml
  test/pj-rehearse-integration/candidate/ci-operator/jobs/super/trooper/super-trooper-master-presubmits.yaml
  test/pj-rehearse-integration/expected_jobs.yaml
  test/pj-rehearse-integration/master/ci-operator/jobs/super/duper/super-duper-ciop-cfg-change-presubmits.yaml
  test/pj-rehearse-integration/master/ci-operator/jobs/super/duper/super-duper-master-presubmits.yaml
  test/pj-rehearse-integration/master/ci-operator/jobs/super/trooper/super-trooper-master-presubmits.yaml
Labels: approved, lgtm, size/L

#107 Correctly clean up temp directory
  cmd/repo-brancher/main.go
Labels: approved, lgtm, size/XS

#100 pj-rehearse - Add configMaps logic on changed templates
  cmd/pj-rehearse/main.go
  cmd/pj-rehearse/main_test.go
  pkg/config/template.go
  pkg/config/template_test.go
  pkg/diffs/diffs.go
  pkg/diffs/diffs_test.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
Labels: approved, lgtm, size/XL

#110 rehearse: simplify termination & cleanup
  cmd/pj-rehearse/main.go
Labels: approved, lgtm, size/M

#111 in --local, create a PR number seeding from current time
  cmd/pj-rehearse/main.go
Labels: approved, lgtm, size/XS

#112 no need to configure template.Name.
  pkg/config/template.go
  pkg/config/template_test.go
Labels: approved, lgtm, size/S

#113 fix configmap name
  pkg/config/template.go
  pkg/config/template_test.go
  pkg/rehearse/jobs.go
Labels: approved, lgtm, size/S

#114 remove unnecessary logging.
  cmd/pj-rehearse/main.go
Labels: approved, lgtm, size/XS

#108 rehearse: Add an option to dump metrics after execution
  cmd/pj-rehearse/main.go
  pkg/rehearse/jobs.go
  pkg/rehearse/metrics.go
  pkg/rehearse/metrics_test.go
Labels: approved, lgtm, size/L

#115 Add a script to validate Prowgen changes do not break openshift/release
  Makefile
  test/validate-prowgen-breaking-changes.sh
Labels: approved, lgtm, size/M

#119 prowgen breaking change detection fix
  test/validate-prowgen-breaking-changes.sh
Labels: approved, lgtm, size/XS

#109 Ensure correct shards for CI Operator config are used
  cmd/config-shard-validator/main.go
  pkg/config/load.go
  pkg/config/load_test.go
Labels: approved, lgtm, size/M

#120 Fix stutter in error message
  cmd/config-shard-validator/main.go
Labels: approved, lgtm, size/XS

#117 Improve job selection on changed ci-op configs
  cmd/pj-rehearse/main.go
  cmd/pj-rehearse/main_test.go
  pkg/diffs/diffs.go
  pkg/diffs/diffs_test.go
  test/pj-rehearse-integration/candidate/ci-operator/config/super/trooper/super-trooper-master.yaml
  test/pj-rehearse-integration/expected_jobs.yaml
  test/pj-rehearse-integration/master/ci-operator/config/super/trooper/super-trooper-master.yaml
Labels: approved, lgtm, size/L

#116 prowgen: prune stale generated jobs
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  pkg/jobconfig/files.go
  pkg/jobconfig/files_test.go
  test/prowgen-integration/data/input/jobs/super/duper/super-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
Labels: approved, lgtm, size/L

#123 rehearse: don't update existing configmaps
  pkg/config/template.go
Labels: approved, lgtm, size/S

#118 rehearse: detect cluster profile changes
  cmd/pj-rehearse/main.go
  cmd/pj-rehearse/main_test.go
  pkg/config/release.go
  pkg/config/release_test.go
  pkg/config/template.go
  pkg/config/template_test.go
  pkg/diffs/diffs.go
  pkg/diffs/diffs_test.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
  pkg/rehearse/metrics.go
Labels: approved, lgtm, size/XL

#124 Generate UPI vsphere tests
  Gopkg.lock
  cmd/ci-operator-prowgen/main.go
  vendor/github.com/openshift/ci-operator/ARCHITECTURE.md
  vendor/github.com/openshift/ci-operator/CONFIGURATION.md
  vendor/github.com/openshift/ci-operator/cmd/ci-operator/main.go
  vendor/github.com/openshift/ci-operator/pkg/api/config.go
  vendor/github.com/openshift/ci-operator/pkg/api/config_test.go
  vendor/github.com/openshift/ci-operator/pkg/api/graph.go
  vendor/github.com/openshift/ci-operator/pkg/api/parameters.go
  vendor/github.com/openshift/ci-operator/pkg/api/types.go
  vendor/github.com/openshift/ci-operator/pkg/defaults/defaults.go
  vendor/github.com/openshift/ci-operator/pkg/load/load_test.go
  vendor/github.com/openshift/ci-operator/pkg/steps/artifacts.go
  vendor/github.com/openshift/ci-operator/pkg/steps/clusterinstall/clusterinstall.go
  vendor/github.com/openshift/ci-operator/pkg/steps/clusterinstall/template.go
  vendor/github.com/openshift/ci-operator/pkg/steps/git_source.go
  vendor/github.com/openshift/ci-operator/pkg/steps/images_ready.go
  vendor/github.com/openshift/ci-operator/pkg/steps/pipeline_image_cache.go
  vendor/github.com/openshift/ci-operator/pkg/steps/project_image.go
  vendor/github.com/openshift/ci-operator/pkg/steps/release/create_release.go
  vendor/github.com/openshift/ci-operator/pkg/steps/release/release_images.go
  vendor/github.com/openshift/ci-operator/pkg/steps/rpm_injection.go
  vendor/github.com/openshift/ci-operator/pkg/steps/source.go
  vendor/github.com/openshift/ci-operator/pkg/steps/template.go
Labels: approved, lgtm, size/XXL

#125 remove main tests
  cmd/pj-rehearse/main_test.go
Labels: approved, lgtm, size/L
