Repository openshift/ci-operator-prowgen, pull requests merged in 2019-04, with the labels that each got.

#128 Update ci-operator vendor
  Gopkg.lock
  vendor/github.com/openshift/ci-operator/cmd/ci-operator/main.go
  vendor/github.com/openshift/ci-operator/pkg/api/types.go
  vendor/github.com/openshift/ci-operator/pkg/steps/clusterinstall/template.go
  vendor/github.com/openshift/ci-operator/pkg/steps/output_image_tag.go
  vendor/github.com/openshift/ci-operator/pkg/steps/output_image_tag_test.go
  vendor/github.com/openshift/ci-operator/pkg/steps/release/promote.go
  vendor/github.com/openshift/ci-operator/pkg/steps/source.go
  vendor/github.com/openshift/ci-operator/pkg/steps/testing.go
Labels: approved, lgtm, size/L

#122 On a template change, rehearse all cluster types.
  cmd/pj-rehearse/main.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
  test/pj-rehearse-integration/candidate/ci-operator/jobs/super/duper/super-duper-master-presubmits.yaml
  test/pj-rehearse-integration/candidate/ci-operator/templates/test-template.yaml
  test/pj-rehearse-integration/expected_jobs.yaml
  test/pj-rehearse-integration/master/ci-operator/jobs/super/duper/super-duper-master-presubmits.yaml
  test/pj-rehearse-integration/run.sh
Labels: approved, lgtm, size/XL

#129 Allow config-brancher to mirror promotion outputs
  cmd/config-brancher/main.go
  cmd/config-brancher/main_test.go
  pkg/promotion/promotion.go
  pkg/promotion/promotion_test.go
Labels: approved, lgtm, size/L

#132 Always put periodics in the misc job config for sanity
  cmd/config-shard-validator/main.go
  pkg/jobconfig/files.go
Labels: approved, lgtm, size/XS

#130 Refactor config brancher to populate many releases
  cmd/config-brancher/main.go
  cmd/config-brancher/main_test.go
  cmd/repo-brancher/main.go
  pkg/promotion/promotion.go
  pkg/promotion/promotion_test.go
Labels: approved, lgtm, size/L

#134 Try deeper clones when failing to push due to missing commits
  cmd/repo-brancher/main.go
Labels: approved, lgtm, size/M

#137 Add a tool to publish merge blocking issues for releases
  cmd/blocking-issue-creator/main.go
Labels: approved, lgtm, size/L

#136 rehearse: check templates in integration tests
  pkg/config/template_test.go
  pkg/rehearse/jobs.go
  test/pj-rehearse-integration/expected.yaml
  test/pj-rehearse-integration/run.sh
Labels: approved, lgtm, size/L

#126 Add a tool for scraping rehearsal metrics from GCS
  Gopkg.lock
  Gopkg.toml
  cmd/pj-rehearse-metrics/pj-rehearse-metrics.go
  cmd/pj-rehearse-metrics/pj-rehearse-metrics_test.go
  vendor/golang.org/x/sync/AUTHORS
  vendor/golang.org/x/sync/CONTRIBUTING.md
  vendor/golang.org/x/sync/CONTRIBUTORS
  vendor/golang.org/x/sync/LICENSE
  vendor/golang.org/x/sync/PATENTS
  vendor/golang.org/x/sync/README.md
  vendor/golang.org/x/sync/codereview.cfg
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sync/errgroup/errgroup_example_md5all_test.go
  vendor/golang.org/x/sync/errgroup/errgroup_test.go
  vendor/golang.org/x/sync/go.mod
  vendor/golang.org/x/sync/semaphore/semaphore.go
  vendor/golang.org/x/sync/semaphore/semaphore_bench_test.go
  vendor/golang.org/x/sync/semaphore/semaphore_example_test.go
  vendor/golang.org/x/sync/semaphore/semaphore_test.go
  vendor/golang.org/x/sync/singleflight/singleflight.go
  vendor/golang.org/x/sync/singleflight/singleflight_test.go
  vendor/golang.org/x/sync/syncmap/map.go
  vendor/golang.org/x/sync/syncmap/map_bench_test.go
  vendor/golang.org/x/sync/syncmap/map_reference_test.go
  vendor/golang.org/x/sync/syncmap/map_test.go
Labels: approved, lgtm, size/XXL, ¯\_(ツ)_/¯

#140 rehearse: add integration test for profiles
  test/pj-rehearse-integration/candidate/cluster/test-deploy/test-profile/vars.yaml
  test/pj-rehearse-integration/expected.yaml
  test/pj-rehearse-integration/master/ci-operator/jobs/super/duper/super-duper-cluster-profile-presubmits.yaml
  test/pj-rehearse-integration/master/cluster/test-deploy/test-profile/vars-origin.yaml
  test/pj-rehearse-integration/master/cluster/test-deploy/test-profile/vars.yaml
Labels: approved, lgtm, size/L

#141 Update merge blocker issue tool
  cmd/blocking-issue-creator/main.go
Labels: approved, lgtm, size/XS

#143 rehearse: last round of small refactorings
  cmd/pj-rehearse/main.go
  pkg/config/template.go
  pkg/config/template_test.go
  pkg/rehearse/jobs.go
  test/pj-rehearse-integration/run.sh
Labels: approved, lgtm, size/L

#144 Store full JobSpec in the metrics
  cmd/pj-rehearse/main.go
  pkg/rehearse/metrics.go
Labels: approved, lgtm, size/S

#142 DPTP-339: Analyze metrics to compute how often rehearsals hit job limits
  cmd/pj-rehearse-metrics/pj-rehearse-metrics.go
  pkg/rehearse/metrics.go
  pkg/rehearse/metrics_test.go
Labels: approved, lgtm, size/L

#145 Remove extra merge blocker issues when they exist
  cmd/blocking-issue-creator/main.go
Labels: approved, lgtm, size/M

#147 sort repos when picking template job
  pkg/rehearse/jobs.go
Labels: approved, lgtm, size/XS

#149 Add support for console test template
  Gopkg.lock
  cmd/ci-operator-prowgen/main.go
  vendor/github.com/openshift/ci-operator/CONFIGURATION.md
  vendor/github.com/openshift/ci-operator/cmd/ci-operator/main.go
  vendor/github.com/openshift/ci-operator/pkg/api/config.go
  vendor/github.com/openshift/ci-operator/pkg/api/types.go
  vendor/github.com/openshift/ci-operator/pkg/steps/output_image_tag.go
  vendor/github.com/openshift/ci-operator/pkg/steps/output_image_tag_test.go
  vendor/github.com/openshift/ci-operator/pkg/steps/release/create_release.go
  vendor/github.com/openshift/ci-operator/pkg/steps/run.go
  vendor/github.com/openshift/ci-operator/pkg/steps/source.go
Labels: approved, lgtm, size/L

#148 Rehearsal metrics: Find and count stale rehearsal occurences
  cmd/pj-rehearse-metrics/pj-rehearse-metrics.go
  pkg/rehearse/metrics.go
  pkg/rehearse/metrics_test.go
Labels: approved, lgtm, size/L

#151 add vsphere cluster type
  pkg/rehearse/jobs.go
Labels: approved, lgtm, size/XS

#127 rehearse: use updateconfig to generate CMs
  cmd/pj-rehearse/main.go
  pkg/config/release.go
  pkg/config/template.go
  pkg/config/template_test.go
  pkg/rehearse/jobs.go
  test/pj-rehearse-integration/expected.yaml
  test/pj-rehearse-integration/master/cluster/ci/config/prow/plugins.yaml
Labels: approved, lgtm, size/L
